### ISSUE TITLE
Marker Explorer: Sort Genesets

### ISSUE THREAD

**Issue by tetomonti** [lia978/carcinogenome#6]
In Marker Explorer (geneset option), the "Select a geneset" should list the genesets in alphabetical order, so as to make the visual search easier.  Ditto for genes and connectivities.

**Comment by tetomonti** [comment]
In Chemical Explorer as well, the "Select chemical" should list the chemicals in alphabetical order, so as to make the visual search easier.

**Comment by lia978** [comment]
added sorting to marker explorer genes and geneset, connectivity was already sorted, 
added ordering to chemical explorer select chemical
