### ISSUE TITLE
Proposal for a new Marker Explorer functionality

### ISSUE THREAD

**Issue by tetomonti** [lia978/carcinogenome#7]
Consider adding a functionality to the Marker Explorer, similar to (sort of the mirror of) the Chemical Explorer functionality. Basically, when selecting a gene, or geneset, or PCL, display a table of the chemicals with their value for that gene/geneset/PCL. Right now, you only show the density plots, but it would be useful to see a ranked list of chemicals for the marker of choice.

**Comment by lia978** [comment]
added table ranked by scores below plots
